# idea of what server config should be maybe. WIP.

users_priv = "r"
users = [
	{ name = "a", pass = "b", priv = "rw" },
	{ name = "b", pass = "b" },
]

certfp_priv = "r"
certfp = [
	{ cert   = "sha1:abcdabcdabcd", priv = "rw" },
	{ pubkey = "sha1:abcdabcdabcd", priv = "rw" },
]

[servers_default]
priv = "rw"
unsafepass = true

[servers.test1]
listen = "1.2.3.4:1234"
defaultpriv = "rw"

[servers.test2]
listen = "1.2.3.4:1234"
defaultpriv = "rw"
tlsauth = "none"

[servers.test3]
listen = "1.2.3.4:1234"


[peers_default]
dial_cert = "filename.pem"

[peers.peer1]
enabled = true

dial = "tcp://1.2.3.4:1234"
dial = "tls://4.3.2.1:4321"
dial_user = { name = "a", pass = "b" }
dial_cert = "filename.pem"

pull = true
pull_user = { name = "a", pass = "b" }
pull_workers = 5

push = true
push_user = { name = "a", pass = "b" }
push_workers = 5

serv_user = { name = "a", pass = "b" }
serv_certfp = "sha1:abcabcabc"

