pre_msg         = ""
post_msg        = ""
pre_line        = "<p class=\"body\">"
post_line       = "</p>"
newline         = ""
pre_quote       = "<span class=\"quote\">"
post_quote      = "</span>"
pre_reference   = "<a class=\"ref\" href=\"#test\">"
post_reference  = "</a>"
truncation_line = "<p class=\"trunc\">message truncated. click <a href=\"/{{urlpath .B.Name}}/thread/{{.T.ID}}#{{.P.ID}}\">here</a> to see whole.</p>"
