pre_msg          = '<div class="body">'
post_msg         = "</div>"
pre_line         = ""
post_line        = ""
newline          = ""
final_newline    = ""
nonfinal_newline = "<br />"
pre_quote        = "<span class=\"quote\">"
post_quote       = "</span>"
pre_reference    = "<a class=\"ref\" href=\"#test\">"
post_reference   = "</a>"
truncation_line  = """
<div><strong class=\"trunc\">\
message truncated. click
<a
 href=\"{{$.N.Root}}/{{escboard .B.Name}}/thread/{{.T.ID}}#p{{.P.ID}}\"
>here</a>
to see whole.\
</strong></div>"""
