pre_msg        = ""
post_msg       = ""
pre_line       = "<p class=\"body\">"
post_line      = "</p>"
newline        = ""
pre_quote      = "<span class=\"quote\">"
post_quote     = "</span>"
pre_reference  = "<a class=\"ref\" href=\"#test\">"
post_reference = "</a>"
